In [1]:
import pandas as pd
df=pd.read_csv('credit_card.csv')

In [2]:
df.head()

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,01-01-2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,01-01-2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,01-01-2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,01-01-2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,01-01-2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Client_Num             10108 non-null  int64
 1   Card_Category          10108 non-null  object
 2   Annual_Fees            10108 non-null  int64
 3   Activation_30_Days     10108 non-null  int64
 4   Customer_Acq_Cost      10108 non-null  int64
 5   Week_Start_Date        10108 non-null  object
 6   Week_Num               10108 non-null  object
 7   Qtr                    10108 non-null  object
 8   current_year           10108 non-null  int64
 9   Credit_Limit           10108 non-null  float64
 10  Total_Revolving_Bal    10108 non-null  int64
 11  Total_Trans_Amt        10108 non-null  int64
 12  Total_Trans_Vol        10108 non-null  int64
 13  Avg_Utilization_Ratio  10108 non-null  float64
 14  Use Chip               10108 non-null  object
 15  Exp Type               10108 non-null  object
 16  Interest_Earned        10108 non-null  float64
 17  Delinquent_Acc         10108 non-null  int64
dtypes: float64(3), int64(9), object(6)
memory usage: 1.4+ MB

In [4]:
df.describe(include='all')

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
count,1.010800e+04,10108,10108.000000,10108.000000,10108.000000,10108,10108,10108,10108.0,10108.000000,10108.000000,10108.000000,10108.000000,10108.000000,10108,10108,10108.000000,10108.000000
unique,NaN,4,NaN,NaN,NaN,52,52,4,NaN,NaN,NaN,NaN,NaN,NaN,3,6,NaN,NaN
top,NaN,Blue,NaN,NaN,NaN,03-12-2023,Week-38,Q3,NaN,NaN,NaN,NaN,NaN,NaN,Swipe,Bills,NaN,NaN
freq,NaN,9214,NaN,NaN,NaN,195,195,2535,NaN,NaN,NaN,NaN,NaN,NaN,7101,2970,NaN,NaN
mean,7.390104e+08,NaN,291.849525,0.574693,96.254056,NaN,NaN,NaN,2023.0,8635.642808,1162.792145,4404.631282,64.864563,0.274851,NaN,NaN,775.957878,0.060744
std,3.673623e+07,NaN,118.339384,0.494414,25.768677,NaN,NaN,NaN,0.0,9093.136113,815.160709,3397.910673,23.475110,0.275720,NaN,NaN,723.952320,0.238872
min,7.080821e+08,NaN,95.000000,0.000000,40.000000,NaN,NaN,NaN,2023.0,1438.300000,0.000000,510.000000,10.000000,0.000000,NaN,NaN,42.140000,0.000000
25%,7.130267e+08,NaN,195.000000,0.000000,79.000000,NaN,NaN,NaN,2023.0,2552.750000,355.500000,2155.750000,45.000000,0.022000,NaN,NaN,326.150000,0.000000
50%,7.179037e+08,NaN,295.000000,1.000000,95.000000,NaN,NaN,NaN,2023.0,4549.000000,1276.500000,3899.500000,67.000000,0.175000,NaN,NaN,559.985000,0.000000
75%,7.727989e+08,NaN,395.000000,1.000000,112.000000,NaN,NaN,NaN,2023.0,11070.250000,1784.000000,4741.000000,81.000000,0.503000,NaN,NaN,962.685000,0.000000
max,8.278908e+08,NaN,500.000000,1.000000,172.000000,NaN,NaN,NaN,2023.0,34516.000000,2517.000000,18484.000000,139.000000,0.999000,NaN,NaN,4785.000000,1.000000

In [5]:
df.isnull().sum()

Client_Num               0
Card_Category            0
Annual_Fees              0
Activation_30_Days       0
Customer_Acq_Cost        0
Week_Start_Date          0
Week_Num                 0
Qtr                      0
current_year             0
Credit_Limit             0
Total_Revolving_Bal      0
Total_Trans_Amt          0
Total_Trans_Vol          0
Avg_Utilization_Ratio    0
Use Chip                 0
Exp Type                 0
Interest_Earned          0
Delinquent_Acc           0
dtype: int64

In [6]:
df.columns

Index(['Client_Num', 'Card_Category', 'Annual_Fees', 'Activation_30_Days',
       'Customer_Acq_Cost', 'Week_Start_Date', 'Week_Num', 'Qtr',
       'current_year', 'Credit_Limit', 'Total_Revolving_Bal',
       'Total_Trans_Amt', 'Total_Trans_Vol', 'Avg_Utilization_Ratio',
       'Use Chip', 'Exp Type', 'Interest_Earned', 'Delinquent_Acc'],
      dtype='object')

In [7]:
# create a column Revenue
df['Revenue'] = df['Annual_Fees'] + df['Total_Trans_Amt'] + df['Interest_Earned']

In [8]:
df.head()

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc,Revenue
0,708082083,Blue,200,0,87,01-01-2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0,19742.21
1,708083283,Blue,445,1,108,01-01-2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0,1506.44
2,708084558,Blue,140,0,106,01-01-2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0,1789.58
3,708085458,Blue,250,1,150,01-01-2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0,4426.40
4,708086958,Blue,320,1,106,01-01-2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1,5693.87

In [9]:
df['Week_Num2'] = df['Week_Num'].str.extract(r'(\d+)').astype(int)

In [10]:
df.head()

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc,Revenue,Week_Num2
0,708082083,Blue,200,0,87,01-01-2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0,19742.21,1
1,708083283,Blue,445,1,108,01-01-2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0,1506.44,1
2,708084558,Blue,140,0,106,01-01-2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0,1789.58,1
3,708085458,Blue,250,1,150,01-01-2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0,4426.40,1
4,708086958,Blue,320,1,106,01-01-2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1,5693.87,1

In [11]:
df['Week_Start_Date'] = pd.to_datetime(df['Week_Start_Date'])

In [12]:
from sqlalchemy import create_engine

#MYSQL connection
username='root'
password='123456'
host='localhost'
port='3306'
database='credit'

engine= create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#write dataframe to MYSQL
table_name="card_credit"
df.to_sql(table_name, engine ,if_exists='replace', index=False)

#Read back sample
pd.read_sql("SELECT * FROM card_credit LIMIT 5;",engine)

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc,Revenue,Week_Num2
0,708082083,Blue,200,0,87,2023-01-01,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0,19742.21,1
1,708083283,Blue,445,1,108,2023-01-01,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0,1506.44,1
2,708084558,Blue,140,0,106,2023-01-01,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0,1789.58,1
3,708085458,Blue,250,1,150,2023-01-01,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0,4426.40,1
4,708086958,Blue,320,1,106,2023-01-01,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1,5693.87,1

In [12]:
df=pd.read_csv('customer.csv')

In [13]:
df.head()

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Client_Num               10108 non-null  int64
 1   Customer_Age             10108 non-null  int64
 2   Gender                   10108 non-null  object
 3   Dependent_Count          10108 non-null  int64
 4   Education_Level          10108 non-null  object
 5   Marital_Status           10108 non-null  object
 6   state_cd                 10108 non-null  object
 7   Zipcode                  10108 non-null  int64
 8   Car_Owner                10108 non-null  object
 9   House_Owner              10108 non-null  object
 10  Personal_loan            10108 non-null  object
 11  contact                  10108 non-null  object
 12  Customer_Job             10108 non-null  object
 13  Income                   10108 non-null  int64
 14  Cust_Satisfaction_Score  10108 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

In [15]:
df.describe(include='all')

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
count,1.010800e+04,10108.000000,10108,10108.000000,10108,10108,10108,10108.000000,10108,10108,10108,10108,10108,10108.000000,10108.000000
unique,NaN,NaN,2,NaN,6,3,28,NaN,2,2,2,3,6,NaN,NaN
top,NaN,NaN,F,NaN,Graduate,Married,CA,NaN,no,no,no,cellular,Selfemployeed,NaN,NaN
freq,NaN,NaN,5880,NaN,4134,5128,2468,NaN,6044,5390,8822,7457,2575,NaN,NaN
mean,7.390104e+08,46.274436,NaN,2.345370,NaN,NaN,NaN,91663.071824,NaN,NaN,NaN,NaN,NaN,56976.101998,3.189256
std,3.673623e+07,8.087876,NaN,1.299486,NaN,NaN,NaN,1693.093868,NaN,NaN,NaN,NaN,NaN,46183.718233,1.263101
min,7.080821e+08,21.000000,NaN,0.000000,NaN,NaN,NaN,53010.000000,NaN,NaN,NaN,NaN,NaN,1250.000000,1.000000
25%,7.130267e+08,41.000000,NaN,1.000000,NaN,NaN,NaN,91750.000000,NaN,NaN,NaN,NaN,NaN,22635.750000,2.000000
50%,7.179037e+08,46.000000,NaN,2.000000,NaN,NaN,NaN,91750.000000,NaN,NaN,NaN,NaN,NaN,44768.500000,3.000000
75%,7.727989e+08,52.000000,NaN,3.000000,NaN,NaN,NaN,91750.000000,NaN,NaN,NaN,NaN,NaN,76392.750000,4.000000
max,8.278908e+08,73.000000,NaN,5.000000,NaN,NaN,NaN,99504.000000,NaN,NaN,NaN,NaN,NaN,239791.000000,5.000000

In [16]:
df.isnull().sum()

Client_Num                 0
Customer_Age               0
Gender                     0
Dependent_Count            0
Education_Level            0
Marital_Status             0
state_cd                   0
Zipcode                    0
Car_Owner                  0
House_Owner                0
Personal_loan              0
contact                    0
Customer_Job               0
Income                     0
Cust_Satisfaction_Score    0
dtype: int64

In [17]:
df.columns

Index(['Client_Num', 'Customer_Age', 'Gender', 'Dependent_Count',
       'Education_Level', 'Marital_Status', 'state_cd', 'Zipcode', 'Car_Owner',
       'House_Owner', 'Personal_loan', 'contact', 'Customer_Job', 'Income',
       'Cust_Satisfaction_Score'],
      dtype='object')

In [18]:
import numpy as np
#  Define your direct conditions
conditions = [
    (df['Customer_Age'] >= 20) & (df['Customer_Age'] <= 30),
    (df['Customer_Age'] > 30) & (df['Customer_Age'] <= 40),
    (df['Customer_Age'] > 40) & (df['Customer_Age'] <= 50),
    (df['Customer_Age'] > 50) & (df['Customer_Age'] <= 60),
    (df['Customer_Age'] > 60)
]

#  Match them to your exact labels
labels = ['20-30', '30-40', '40-50', '50-60', '60+']

#  Apply directly to the column
df['Age_Group'] = np.select(conditions, labels, default='Unknown')

In [19]:
df

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Age_Group
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3,20-30
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2,60+
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2,30-40
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1,30-40
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1,40-50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5,40-50
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3,40-50
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3,40-50
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4,40-50
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4,40-50

In [20]:

conditions = [
    df['Income'] < 35000,                               # Less than or equal to 35k
    (df['Income'] >= 35000) & (df['Income'] < 70000),     # Between 35k and 70k
    df['Income'] >= 70000                                # Greater than or equal to 70k
]

# 2. Match them to your exact labels
labels = ['Low', 'Medium', 'High']

# 3. Create the new column instantly for the whole dataset
df['Income_Group'] = np.select(conditions, labels, default='Unknown')

In [21]:
df

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Age_Group,Income_Group
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3,20-30,High
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2,60+,Low
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2,30-40,Low
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1,30-40,Medium
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1,40-50,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10103,827695683,44,M,3,Graduate,Single,NV,91750,yes,yes,yes,unknown,Selfemployeed,44903,5,40-50,Medium
10104,827703258,48,M,3,Unknown,Unknown,TX,91750,no,yes,no,cellular,Selfemployeed,73655,3,40-50,High
10105,827712108,47,M,4,Graduate,Married,NY,91750,yes,no,no,cellular,Selfemployeed,62287,3,40-50,Medium
10106,827888433,42,F,3,Graduate,Married,TX,91750,no,no,no,cellular,White-collar,21390,4,40-50,Low
10107,827890758,47,M,4,High School,Married,NY,91750,no,yes,no,cellular,Selfemployeed,42187,4,40-50,Medium

In [22]:
from sqlalchemy import create_engine

#MYSQL connection
username='root'
password='123456'
host='localhost'
port='3306'
database='credit'

engine= create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#write dataframe to MYSQL
table_name="customer_credit"
df.to_sql(table_name, engine ,if_exists='replace', index=False)

#Read back sample
pd.read_sql("SELECT * FROM customer_credit LIMIT 5;",engine)

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Age_Group,Income_Group
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3,20-30,High
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2,60+,Low
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2,30-40,Low
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1,30-40,Medium
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1,40-50,Medium